### ISSUE TITLE
Art in mobile

### ISSUE THREAD

**Issue by BlackIQ** [Qiamast/Qiamast#1]
Hi,

You have a nice art text in your README. but in mobile devices or small screens it is not showing as how to shows in desktop or big screens.

What I suggest, is to create it as a SVG file. Then you show the SVG and there will be no issues.

hope you fix it and enjoyed my suggest.

Regards.

Amir.

![0EDEB612-DC43-4CCE-ACD6-C7B802935FE8](https://user-images.githubusercontent.com/55284339/160301653-bd100608-7c52-4acc-9e0b-0750a576ff5d.png)

**Comment by Qiamast** [comment]
Hi Amir 👋 thank you for creating the issue. I will try to solve this problem
I know SVG format and like it but I like to use ASCII ART for README.MD. 
Whenever I find a good solution to handle this problem, I will try it
